张量 Tensors
=======

张量是一种Pytorch中使用的基础的数据结构，非常类似于数组和矩阵。
Pytorch张量来存储模型的输入和输出，以及模型的参数。

张量与NumPy中的ndarrays类似，区别在于张量可以运行在GPU上，而且针对自动微分进行了优化。
Tensors和NumPy数组通常可以共享相同的底层内存，因此无需复制数据。

In [1]:
import torch
import numpy as np

张量初始化
=====================

**从数据初始化**

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**从Numpy数组初始化**

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**从另一个张量初始化**

In [4]:
x_ones = torch.ones_like(x_data)
# x_ones的属性与x_data相同
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
# 覆盖x_data的属性
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0768, 0.8190],
        [0.3009, 0.3592]]) 



**使用随机或固定值**

In [5]:
shape = (2,3,) #指定张量的形状

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4171, 0.9678, 0.0474],
        [0.9912, 0.3636, 0.0700]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


张量的属性
======================

张量的属性包括形状、数据类型、存储设备.


In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Operations on Tensors
=====================

Pytorch支持超过100种张量运算，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等
（https://pytorch.org/docs/stable/torch.html）。

默认情况下，张量是在CPU上创建的。我们需要明确地使用“.to(device)”方法将其移动位置。


In [7]:
# 把张量转移到GPU
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

**索引和切片:**

In [8]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**张量合并**

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**计算操作**

In [10]:
# 实现矩阵相乘的三种写法，tensor.T实现矩阵转置
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 计算Hadamard积的三种写法
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**单元素张量**
如果张量中只有一个元素，则可以用“item()”方法将其转为Python数值:

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


张量转为NumPy数组
=================

CPU上的张量和NumPy数组可以共享它们的底层内存位置，更改其中一个将会更改另一个。

In [12]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy数组转为张量
=================

In [13]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
